def lint()
    use_frameworks!
    pod 'SwiftLint'
end

def pods()
  use_frameworks!
  pod 'RepoName', :path => "../"
  lint()
end

target 'iOS' do
  platform :ios, '9.0'
  pods()
end

target 'macOS' do
  platform :osx, '10.10'
  pods()
end
